CREATE DATABASE CRUD;
USE CRUD;
CREATE TABLE Contato (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    idade INT NOT NULL,
    email VARCHAR(30) NOT NULL,
    ddd INT NOT NULL,
    telefone BIGINT NOT NULL
);